package baseDatosAlumno;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of alumnos.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Alumnos implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** numAlumnos. */
	private String numalumnos;

	/** nombre. */
	private String nombre;

	/** grupo. */
	private String grupo;

	/** The set of cursan. */
	private Set<Cursan> cursanSet;

	/** The set of hacen. */
	private Set<Hacen> hacenSet;

	/** The set of new_table. */
	private Set<NewTable> newTableSet;

	/**
	 * Constructor.
	 */
	public Alumnos() {
		this.cursanSet = new HashSet<Cursan>();
		this.hacenSet = new HashSet<Hacen>();
		this.newTableSet = new HashSet<NewTable>();
	}

	/**
	 * Set the numAlumnos.
	 * 
	 * @param numalumnos
	 *            numAlumnos
	 */
	public void setNumalumnos(String numalumnos) {
		this.numalumnos = numalumnos;
	}

	/**
	 * Get the numAlumnos.
	 * 
	 * @return numAlumnos
	 */
	public String getNumalumnos() {
		return this.numalumnos;
	}

	/**
	 * Set the nombre.
	 * 
	 * @param nombre
	 *            nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the nombre.
	 * 
	 * @return nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the grupo.
	 * 
	 * @param grupo
	 *            grupo
	 */
	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	/**
	 * Get the grupo.
	 * 
	 * @return grupo
	 */
	public String getGrupo() {
		return this.grupo;
	}

	/**
	 * Set the set of the cursan.
	 * 
	 * @param cursanSet
	 *            The set of cursan
	 */
	public void setCursanSet(Set<Cursan> cursanSet) {
		this.cursanSet = cursanSet;
	}

	/**
	 * Add the cursan.
	 * 
	 * @param cursan
	 *            cursan
	 */
	public void addCursan(Cursan cursan) {
		this.cursanSet.add(cursan);
	}

	/**
	 * Get the set of the cursan.
	 * 
	 * @return The set of cursan
	 */
	public Set<Cursan> getCursanSet() {
		return this.cursanSet;
	}

	/**
	 * Set the set of the hacen.
	 * 
	 * @param hacenSet
	 *            The set of hacen
	 */
	public void setHacenSet(Set<Hacen> hacenSet) {
		this.hacenSet = hacenSet;
	}

	/**
	 * Add the hacen.
	 * 
	 * @param hacen
	 *            hacen
	 */
	public void addHacen(Hacen hacen) {
		this.hacenSet.add(hacen);
	}

	/**
	 * Get the set of the hacen.
	 * 
	 * @return The set of hacen
	 */
	public Set<Hacen> getHacenSet() {
		return this.hacenSet;
	}

	/**
	 * Set the set of the new_table.
	 * 
	 * @param newTableSet
	 *            The set of new_table
	 */
	public void setNewTableSet(Set<NewTable> newTableSet) {
		this.newTableSet = newTableSet;
	}

	/**
	 * Add the new_table.
	 * 
	 * @param newTable
	 *            new_table
	 */
	public void addNewTable(NewTable newTable) {
		this.newTableSet.add(newTable);
	}

	/**
	 * Get the set of the new_table.
	 * 
	 * @return The set of new_table
	 */
	public Set<NewTable> getNewTableSet() {
		return this.newTableSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((numalumnos == null) ? 0 : numalumnos.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Alumnos other = (Alumnos) obj;
		if (numalumnos == null) {
			if (other.numalumnos != null) {
				return false;
			}
		} else if (!numalumnos.equals(other.numalumnos)) {
			return false;
		}
		return true;
	}

}
