package baseDatosAlumno;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of asignaturas.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Asignaturas implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** numAsignatura. */
	private Integer numasignatura;

	/** nombre. */
	private String nombre;

	/** The set of cursan. */
	private Set<Cursan> cursanSet;

	/** The set of profesores. */
	private Set<Profesores> profesoresSet;

	/**
	 * Constructor.
	 */
	public Asignaturas() {
		this.cursanSet = new HashSet<Cursan>();
		this.profesoresSet = new HashSet<Profesores>();
	}

	/**
	 * Set the numAsignatura.
	 * 
	 * @param numasignatura
	 *            numAsignatura
	 */
	public void setNumasignatura(Integer numasignatura) {
		this.numasignatura = numasignatura;
	}

	/**
	 * Get the numAsignatura.
	 * 
	 * @return numAsignatura
	 */
	public Integer getNumasignatura() {
		return this.numasignatura;
	}

	/**
	 * Set the nombre.
	 * 
	 * @param nombre
	 *            nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the nombre.
	 * 
	 * @return nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the set of the cursan.
	 * 
	 * @param cursanSet
	 *            The set of cursan
	 */
	public void setCursanSet(Set<Cursan> cursanSet) {
		this.cursanSet = cursanSet;
	}

	/**
	 * Add the cursan.
	 * 
	 * @param cursan
	 *            cursan
	 */
	public void addCursan(Cursan cursan) {
		this.cursanSet.add(cursan);
	}

	/**
	 * Get the set of the cursan.
	 * 
	 * @return The set of cursan
	 */
	public Set<Cursan> getCursanSet() {
		return this.cursanSet;
	}

	/**
	 * Set the set of the profesores.
	 * 
	 * @param profesoresSet
	 *            The set of profesores
	 */
	public void setProfesoresSet(Set<Profesores> profesoresSet) {
		this.profesoresSet = profesoresSet;
	}

	/**
	 * Add the profesores.
	 * 
	 * @param profesores
	 *            profesores
	 */
	public void addProfesores(Profesores profesores) {
		this.profesoresSet.add(profesores);
	}

	/**
	 * Get the set of the profesores.
	 * 
	 * @return The set of profesores
	 */
	public Set<Profesores> getProfesoresSet() {
		return this.profesoresSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((numasignatura == null) ? 0 : numasignatura.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Asignaturas other = (Asignaturas) obj;
		if (numasignatura == null) {
			if (other.numasignatura != null) {
				return false;
			}
		} else if (!numasignatura.equals(other.numasignatura)) {
			return false;
		}
		return true;
	}

}
