package baseDatosAlumno;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of elaboran.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Elaboran implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** practicas. */
	private Practicas practicas;

	/** profesores. */
	private Profesores profesores;

	/** fechaPP. */
	private Date fechapp;

	/**
	 * Constructor.
	 */
	public Elaboran() {
	}

	/**
	 * Set the practicas.
	 * 
	 * @param practicas
	 *            practicas
	 */
	public void setPracticas(Practicas practicas) {
		this.practicas = practicas;
	}

	/**
	 * Get the practicas.
	 * 
	 * @return practicas
	 */
	public Practicas getPracticas() {
		return this.practicas;
	}

	/**
	 * Set the profesores.
	 * 
	 * @param profesores
	 *            profesores
	 */
	public void setProfesores(Profesores profesores) {
		this.profesores = profesores;
	}

	/**
	 * Get the profesores.
	 * 
	 * @return profesores
	 */
	public Profesores getProfesores() {
		return this.profesores;
	}

	/**
	 * Set the fechaPP.
	 * 
	 * @param fechapp
	 *            fechaPP
	 */
	public void setFechapp(Date fechapp) {
		this.fechapp = fechapp;
	}

	/**
	 * Get the fechaPP.
	 * 
	 * @return fechaPP
	 */
	public Date getFechapp() {
		return this.fechapp;
	}


}
