package baseDatosAlumno;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of examenes.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Examenes implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** numExamen. */
	private Integer numexamen;

	/** numPreguntas. */
	private Integer numpreguntas;

	/** fecha. */
	private Date fecha;

	/** The set of hacen. */
	private Set<Hacen> hacenSet;

	/**
	 * Constructor.
	 */
	public Examenes() {
		this.hacenSet = new HashSet<Hacen>();
	}

	/**
	 * Set the numExamen.
	 * 
	 * @param numexamen
	 *            numExamen
	 */
	public void setNumexamen(Integer numexamen) {
		this.numexamen = numexamen;
	}

	/**
	 * Get the numExamen.
	 * 
	 * @return numExamen
	 */
	public Integer getNumexamen() {
		return this.numexamen;
	}

	/**
	 * Set the numPreguntas.
	 * 
	 * @param numpreguntas
	 *            numPreguntas
	 */
	public void setNumpreguntas(Integer numpreguntas) {
		this.numpreguntas = numpreguntas;
	}

	/**
	 * Get the numPreguntas.
	 * 
	 * @return numPreguntas
	 */
	public Integer getNumpreguntas() {
		return this.numpreguntas;
	}

	/**
	 * Set the fecha.
	 * 
	 * @param fecha
	 *            fecha
	 */
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/**
	 * Get the fecha.
	 * 
	 * @return fecha
	 */
	public Date getFecha() {
		return this.fecha;
	}

	/**
	 * Set the set of the hacen.
	 * 
	 * @param hacenSet
	 *            The set of hacen
	 */
	public void setHacenSet(Set<Hacen> hacenSet) {
		this.hacenSet = hacenSet;
	}

	/**
	 * Add the hacen.
	 * 
	 * @param hacen
	 *            hacen
	 */
	public void addHacen(Hacen hacen) {
		this.hacenSet.add(hacen);
	}

	/**
	 * Get the set of the hacen.
	 * 
	 * @return The set of hacen
	 */
	public Set<Hacen> getHacenSet() {
		return this.hacenSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((numexamen == null) ? 0 : numexamen.hashCode());
		result = prime * result + ((fecha == null) ? 0 : fecha.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Examenes other = (Examenes) obj;
		if (numexamen == null) {
			if (other.numexamen != null) {
				return false;
			}
		} else if (!numexamen.equals(other.numexamen)) {
			return false;
		}
		if (fecha == null) {
			if (other.fecha != null) {
				return false;
			}
		} else if (!fecha.equals(other.fecha)) {
			return false;
		}
		return true;
	}

}
