package baseDatosAlumno;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of new_table.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class NewTable implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** alumnos. */
	private Alumnos alumnos;

	/** practicas. */
	private Practicas practicas;

	/** nota. */
	private Float nota;

	/** fecha. */
	private Date fecha;

	/**
	 * Constructor.
	 */
	public NewTable() {
	}

	/**
	 * Set the alumnos.
	 * 
	 * @param alumnos
	 *            alumnos
	 */
	public void setAlumnos(Alumnos alumnos) {
		this.alumnos = alumnos;
	}

	/**
	 * Get the alumnos.
	 * 
	 * @return alumnos
	 */
	public Alumnos getAlumnos() {
		return this.alumnos;
	}

	/**
	 * Set the practicas.
	 * 
	 * @param practicas
	 *            practicas
	 */
	public void setPracticas(Practicas practicas) {
		this.practicas = practicas;
	}

	/**
	 * Get the practicas.
	 * 
	 * @return practicas
	 */
	public Practicas getPracticas() {
		return this.practicas;
	}

	/**
	 * Set the nota.
	 * 
	 * @param nota
	 *            nota
	 */
	public void setNota(Float nota) {
		this.nota = nota;
	}

	/**
	 * Get the nota.
	 * 
	 * @return nota
	 */
	public Float getNota() {
		return this.nota;
	}

	/**
	 * Set the fecha.
	 * 
	 * @param fecha
	 *            fecha
	 */
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/**
	 * Get the fecha.
	 * 
	 * @return fecha
	 */
	public Date getFecha() {
		return this.fecha;
	}


}
