package baseDatosAlumno;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of practicas.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Practicas implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** codPractica. */
	private Integer codpractica;

	/** titulo. */
	private String titulo;

	/** nivel. */
	private String nivel;

	/** The set of elaboran. */
	private Set<Elaboran> elaboranSet;

	/** The set of new_table. */
	private Set<NewTable> newTableSet;

	/**
	 * Constructor.
	 */
	public Practicas() {
		this.elaboranSet = new HashSet<Elaboran>();
		this.newTableSet = new HashSet<NewTable>();
	}

	/**
	 * Set the codPractica.
	 * 
	 * @param codpractica
	 *            codPractica
	 */
	public void setCodpractica(Integer codpractica) {
		this.codpractica = codpractica;
	}

	/**
	 * Get the codPractica.
	 * 
	 * @return codPractica
	 */
	public Integer getCodpractica() {
		return this.codpractica;
	}

	/**
	 * Set the titulo.
	 * 
	 * @param titulo
	 *            titulo
	 */
	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	/**
	 * Get the titulo.
	 * 
	 * @return titulo
	 */
	public String getTitulo() {
		return this.titulo;
	}

	/**
	 * Set the nivel.
	 * 
	 * @param nivel
	 *            nivel
	 */
	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

	/**
	 * Get the nivel.
	 * 
	 * @return nivel
	 */
	public String getNivel() {
		return this.nivel;
	}

	/**
	 * Set the set of the elaboran.
	 * 
	 * @param elaboranSet
	 *            The set of elaboran
	 */
	public void setElaboranSet(Set<Elaboran> elaboranSet) {
		this.elaboranSet = elaboranSet;
	}

	/**
	 * Add the elaboran.
	 * 
	 * @param elaboran
	 *            elaboran
	 */
	public void addElaboran(Elaboran elaboran) {
		this.elaboranSet.add(elaboran);
	}

	/**
	 * Get the set of the elaboran.
	 * 
	 * @return The set of elaboran
	 */
	public Set<Elaboran> getElaboranSet() {
		return this.elaboranSet;
	}

	/**
	 * Set the set of the new_table.
	 * 
	 * @param newTableSet
	 *            The set of new_table
	 */
	public void setNewTableSet(Set<NewTable> newTableSet) {
		this.newTableSet = newTableSet;
	}

	/**
	 * Add the new_table.
	 * 
	 * @param newTable
	 *            new_table
	 */
	public void addNewTable(NewTable newTable) {
		this.newTableSet.add(newTable);
	}

	/**
	 * Get the set of the new_table.
	 * 
	 * @return The set of new_table
	 */
	public Set<NewTable> getNewTableSet() {
		return this.newTableSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codpractica == null) ? 0 : codpractica.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Practicas other = (Practicas) obj;
		if (codpractica == null) {
			if (other.codpractica != null) {
				return false;
			}
		} else if (!codpractica.equals(other.codpractica)) {
			return false;
		}
		return true;
	}

}
