package baseDatosAlumno;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of profesores.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Profesores implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** numProfesores. */
	private Integer numprofesores;

	/** nombreProfesor. */
	private String nombreprofesor;

	/** asignaturas. */
	private Asignaturas asignaturas;

	/** The set of elaboran. */
	private Set<Elaboran> elaboranSet;

	/**
	 * Constructor.
	 */
	public Profesores() {
		this.elaboranSet = new HashSet<Elaboran>();
	}

	/**
	 * Set the numProfesores.
	 * 
	 * @param numprofesores
	 *            numProfesores
	 */
	public void setNumprofesores(Integer numprofesores) {
		this.numprofesores = numprofesores;
	}

	/**
	 * Get the numProfesores.
	 * 
	 * @return numProfesores
	 */
	public Integer getNumprofesores() {
		return this.numprofesores;
	}

	/**
	 * Set the nombreProfesor.
	 * 
	 * @param nombreprofesor
	 *            nombreProfesor
	 */
	public void setNombreprofesor(String nombreprofesor) {
		this.nombreprofesor = nombreprofesor;
	}

	/**
	 * Get the nombreProfesor.
	 * 
	 * @return nombreProfesor
	 */
	public String getNombreprofesor() {
		return this.nombreprofesor;
	}

	/**
	 * Set the asignaturas.
	 * 
	 * @param asignaturas
	 *            asignaturas
	 */
	public void setAsignaturas(Asignaturas asignaturas) {
		this.asignaturas = asignaturas;
	}

	/**
	 * Get the asignaturas.
	 * 
	 * @return asignaturas
	 */
	public Asignaturas getAsignaturas() {
		return this.asignaturas;
	}

	/**
	 * Set the set of the elaboran.
	 * 
	 * @param elaboranSet
	 *            The set of elaboran
	 */
	public void setElaboranSet(Set<Elaboran> elaboranSet) {
		this.elaboranSet = elaboranSet;
	}

	/**
	 * Add the elaboran.
	 * 
	 * @param elaboran
	 *            elaboran
	 */
	public void addElaboran(Elaboran elaboran) {
		this.elaboranSet.add(elaboran);
	}

	/**
	 * Get the set of the elaboran.
	 * 
	 * @return The set of elaboran
	 */
	public Set<Elaboran> getElaboranSet() {
		return this.elaboranSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((numprofesores == null) ? 0 : numprofesores.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Profesores other = (Profesores) obj;
		if (numprofesores == null) {
			if (other.numprofesores != null) {
				return false;
			}
		} else if (!numprofesores.equals(other.numprofesores)) {
			return false;
		}
		return true;
	}

}
